/**
 * Shared wire protocol for the DeepSeek Harness SDK runtime: the
 * newline-delimited JSON-RPC stdio transport plus the named request, result,
 * and notification types both wire ends speak. The runtime server plugin
 * (`@deepseek-ai/dsh-sdk-jsonrpc-server`) serves this protocol; SDK clients
 * (`@deepseek-ai/dsh-sdk-client`, the Python SDK) drive it.
 *
 * @module @deepseek-ai/dsh-sdk-protocol
 */

export { JsonRpcLineTransport, JsonRpcResponseError } from './transport.ts'
export type { JsonRpcTransportPeer } from './transport.ts'
export type {
  AgentPresetWire,
  AgentPresetsListResult,
  AttachmentImageLimitsResult,
  AttachmentSaveImageParams,
  AttachmentSaveImageResult,
  CommandDescriptor,
  CommandExecuteParams,
  CommandExecuteResult,
  CommandListResult,
  HarnessSdkNotificationMap,
  HarnessSdkRequestMap,
  InitializeParams,
  InitializeResult,
  InteractionRequestedNotification,
  InteractionRequestId,
  InteractionResolvedNotification,
  InteractionRespondParams,
  InteractionRespondResult,
  ModelCatalogEntry,
  ModelCatalogFailure,
  ModelCatalogReasoning,
  ModelCatalogReasoningEffort,
  ModelCatalogResult,
  ModelProviderCatalog,
  ProviderAuthCancelParams,
  ProviderAuthCancelResult,
  ProviderAuthEventNotification,
  ProviderAuthFinishedNotification,
  ProviderAuthInfoParams,
  ProviderAuthInfoResult,
  ProviderAuthLogoutParams,
  ProviderAuthLogoutResult,
  ProviderAuthMethod,
  ProviderAuthPrompt,
  ProviderAuthPromptNotification,
  ProviderAuthPromptResolvedNotification,
  ProviderAuthRespondParams,
  ProviderAuthRespondResult,
  ProviderAuthStartParams,
  ProviderAuthStartResult,
  SdkEncodedImageBlock,
  SdkPromptContentBlock,
  SdkRunStatus,
  SessionCancelResult,
  SessionCloseResult,
  SessionControlParams,
  SessionEventNotification,
  SessionHistoryEvent,
  SessionHistoryResult,
  SessionListEntry,
  SessionListResult,
  SessionResumeResult,
  SessionStatusNotification,
  SessionPromptParams,
  SessionPromptResult,
  SessionSelectModelParams,
  SessionSelectModelResult,
  SettingsGetResult,
  SettingsNamespaceWire,
  SettingsSetParams,
  SettingsSetResult,
  SkillSummaryWire,
  SkillsListParams,
  SkillsListResult,
  SubagentFinishedNotification,
  SubagentStartedNotification,
} from './types.ts'
